-- Generated by Oracle SQL Developer REST Data Services 4.2.0.17.089.1709
-- Exported REST Definitions from ORDS Schema Version 3.0.9.348.07.16
-- Schema: BEACON   Date: Tue Sep 12 12:56:58 MDT 2017
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'BEACON',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'beacon',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'Beacon',
      p_base_path      => '/beacon/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Beacon',
      p_pattern        => 'alert/{scanner_id}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Beacon',
      p_pattern        => 'alert/{scanner_id}',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT ''application/json'',
        json_arrayagg(json_object(''name'' VALUE name,
                   ''description'' VALUE description,
                   ''ltd'' VALUE ltd,
                   ''startHour'' VALUE starthour,
                   ''hours'' VALUE hours,
                   ''actions'' VALUE (select json_arrayagg(json_object(''action'' VALUE actions.action,
                                                                     ''value'' VALUE actions.value)
                                                        )
                                      FROM actions
                                     WHERE actions.id in (select action_id
                                                            from alert_actions
                                                           where alert_id = alerts.id)
                                    )
                                  )
                  )
FROM
    alerts
WHERE
    scanner_id = :scanner_id'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Beacon',
      p_pattern        => 'alert/{scanner_id}',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO alerts (
        scanner_id,
        name,
        description,
        func
    ) VALUES (
        :scanner_id,
        :name,
        :description,
        :func
    );

END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Beacon',
      p_pattern        => 'scan',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Beacon',
      p_pattern        => 'scan',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select *
  from reading
  order by created_on'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Beacon',
      p_pattern        => 'scan',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    newid   reading.id%TYPE;
BEGIN
    INSERT INTO reading (
        scanner_id,
        beacon_id,
        distance
    ) VALUES (
        :scannerId,
        :beaconId,
        :distance
    ) RETURNING id INTO newid;

    :newid := newid;
    :status := 201;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'Beacon',
      p_pattern            => 'scan',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'Beacon',
      p_pattern            => 'scan',
      p_method             => 'POST',
      p_name               => 'newid',
      p_bind_variable_name => 'newid',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      


  COMMIT; 
END;